version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "panda-crm-system"
s3_bucket = ""
s3_prefix = "panda-crm"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
confirm_changeset = true