AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Panda CRM System

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, prod]

Resources:
  # DynamoDB Tables
  ContactsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub panda-contacts-${Environment}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  CollectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub panda-collections-${Environment}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub panda-config-${Environment}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  EmployeesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub panda-employees-${Environment}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Lambda Function
  PandaCRMFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub panda-crm-${Environment}
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 30
      Environment:
        Variables:
          EMPLOYEES_TABLE: !Ref EmployeesTable
          CONTACTS_TABLE: !Ref ContactsTable
          COLLECTIONS_TABLE: !Ref CollectionsTable
          CONFIG_TABLE: !Ref ConfigTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ContactsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CollectionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ConfigTable
        - DynamoDBCrudPolicy:
            TableName: !Ref EmployeesTable
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref PandaAPI

  # API Gateway
  PandaAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub panda-crm-api-${Environment}
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,Accept'"
        AllowOrigin: "'*'"

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub https://${PandaAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
    Export:
      Name: !Sub ${AWS::StackName}-ApiUrl

  ContactsTable:
    Description: Contacts DynamoDB Table
    Value: !Ref ContactsTable

  CollectionsTable:
    Description: Collections DynamoDB Table
    Value: !Ref CollectionsTable